/**
 * TrapEndTypes.d.ts — indesign-uxp-types
 * Adobe InDesign 2026 (21.x) UXP scripting DOM declarations.
 * Version: 1.0.0 · Updated: 2026-09-28
 * Author: Vlad Vladila (Krommatine Systems) · https://github.com/vamitul/indesign-uxp-types
 */
import type { EnumComparand, Enumeration, Enumerator, __val} from "../_base/Enums";



declare const __TrapEndTypes: unique symbol;


/*----------------------------------------/
/   Internal enumerator interfaces        /
/       -- Not exported --                /
/----------------------------------------*/


interface TrapEndTypes extends Enumerator {
  /** True when `other` is this same enumerator. Enumerators are objects — `===` is always false. */
  equals(other: EnumComparand<TrapEndTypes>): boolean;

  /**
   * @internal **WARNING:** `__TrapEndTypes` is a phantom type for compiler strictness only. 
   * It DOES NOT exist at runtime. Do not evaluate it in your logic.
   */
  readonly [__TrapEndTypes]: never;
}


/**
 * Shapes the end of the trap to keep it away from the intersecting object.
 */
interface TrapEndTypes_MITER_TRAP_ENDS extends TrapEndTypes {
  /**
   * @internal **WARNING:** `__val` is a phantom type for compiler strictness only. 
   * It DOES NOT exist at runtime. Do not evaluate it in your logic.
   */
  readonly [__val]: 1953525093;
}

/**
 * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
 */
interface TrapEndTypes_OVERLAP_TRAP_ENDS extends TrapEndTypes {
  /**
   * @internal **WARNING:** `__val` is a phantom type for compiler strictness only. 
   * It DOES NOT exist at runtime. Do not evaluate it in your logic.
   */
  readonly [__val]: 1953525612;
}



/*----------------------------------------/
/                Exports                  /
/----------------------------------------*/

/**
 * Shape options for the intersection of three-way traps.
 */
export declare namespace TrapEndTypes {
/**
 * Shapes the end of the trap to keep it away from the intersecting object.
 */
type MITER_TRAP_ENDS = TrapEndTypes_MITER_TRAP_ENDS;

/**
 * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
 */
type OVERLAP_TRAP_ENDS = TrapEndTypes_OVERLAP_TRAP_ENDS;

}
/**
 * Shape options for the intersection of three-way traps.
 */
export declare const TrapEndTypes: typeof Enumeration & {

  /**
   * Shapes the end of the trap to keep it away from the intersecting object.
   */
  readonly MITER_TRAP_ENDS: TrapEndTypes_MITER_TRAP_ENDS;
  /**
   * Shapes the end of the trap to keep it away from the intersecting object.
   */
  readonly miterTrapEnds: TrapEndTypes_MITER_TRAP_ENDS;
  /**
   * Shapes the end of the trap to keep it away from the intersecting object.
   */
  readonly mitertrapends: TrapEndTypes_MITER_TRAP_ENDS;

  /**
   * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
   */
  readonly OVERLAP_TRAP_ENDS: TrapEndTypes_OVERLAP_TRAP_ENDS;
  /**
   * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
   */
  readonly overlapTrapEnds: TrapEndTypes_OVERLAP_TRAP_ENDS;
  /**
   * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
   */
  readonly overlaptrapends: TrapEndTypes_OVERLAP_TRAP_ENDS;

}
